### PR TITLE
Gui/DopeSheet: add parent QModelIndex

### LINKED ISSUE #1052: (Bug): Dopesheet crashes when clicking item in the hierarchy view
### Make sure to follow our issue report guidelines

- [x] I'm using the latest version of Natron (not required but recommended)
- [x] I've restarted Natron and the issue persists
- [x] I've run Natron via the [command line](https://natron.readthedocs.io/en/rb-2.4/devel/natronexecution.html) and the issue persists
- [x] I've followed the [contributing guidelines](https://github.com/NatronGitHub/Natron/blob/RB-2.4/CONTRIBUTING.md) to the best of my understanding
- [x] My issue is not on the [issue tracker](https://github.com/NatronGitHub/Natron/issues?q=is%3Aissue+type%3Abug) or in a [pull request](https://github.com/NatronGitHub/Natron/pulls) already (go search for it and dig around a little bit!)
- [x] This bug is reproducible

### Natron version

2.6.0

### Operating system

Window 10

### System specs

I get a crash everytime I click on an item on the dopesheet hierarchy view. I tracked this bug down and it happens in the
```
HierarchyViewSelectionModel::selectChildren
```
method. I don't understand what that function should do exactly, but I commented out the recursion line in the meantime to avoid infinite recursive call and finally stack overflow.
Cheers.

### Did you install Natron using the official installer?

- [ ] Yes, I used the official installer
- [ ] No, I installed from a binary archive
- [x] No, I compiled Natron from sources
- [ ] No, I installed Natron via another method

### Custom installation path

_No response_

### What were you trying to do?

Moving keyframes in the dopesheet view

### What did you expect to happen? What happened instead?

Crash

### Step-by-step reproduction instructions

Start natron
Create some nodes
Add keyframes
Go to the dopesheet
click on an item in the dependency view
*Crash*

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by rodlie**
Should fix issue #1052

### CODE REVIEW

File: Gui/DopeSheetHierarchyView.cpp [hunk 1]
```diff
@@ -143,7 +143,7 @@ HierarchyViewSelectionModel::selectChildren(const QModelIndex &index,
         }
 
         ++row;
-        childIndex = index.model()->index(row, 0);
+        childIndex = index.model()->index(row, 0, index);
```
Comment (acolwell) [inline Gui/DopeSheetHierarchyView.cpp:146]: Is this equivalent to childIndex = childIndex.siblingRow(row);  ? If so, maybe use this instead since looks a little more like an iterator?

I don't have a strong opinion on this so if you prefer what you have here and below that is fine by me.

**Review by acolwell — APPROVED** [review]
